language: go


go:
  - 1.9.x
  - tip

before_script:
  - go get -t -v github.com/smallnest/gomemcached

script:
 - go build .

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always